### ISSUE TITLE
[Batch validate] Issue with NotEmptyValidator()

### ISSUE THREAD

**Issue by robinschmid** [mwang87/GNPS_quickstart#14]
Hey everyone,
Hey @mwang87,

I looked at the validator.py and the ``NotEmptyValidator`` seems to treat cells with N/A as empty. Maybe the problem is more with the way the files are parsed. N/A might not be parsed as a String.  

Does anyone know how to fix it?
@kcweldon20 

this would need to be changed for all N/A columns (optional).

Cheers
Robin

Link to code:
https://github.com/mwang87/GNPS_quickstart/blob/98a13303681f8be322fa1fe7a6a8fd50c764ea63/batch_validator.py#L36-L44

See related issues
see related issue and test files: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/226
#12 #13 

Documentation 
https://ccms-ucsd.github.io/GNPSDocumentation/batchupload/

![image](https://user-images.githubusercontent.com/10366914/67887313-52b19700-fb4b-11e9-8860-7f4e7acb0683.png)

**Comment by mwang87** [comment]
Actually, I think this is an error with pandas. I'm finishing up work to make this all work. Unit tests are doing well, but slight change to web server should fix the issue.

**Comment by mwang87** [comment]
bugs fixed and deployed.
